# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2025-2026 Polycode Limited
name: Check AWS deployment credentials

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/check-aws-access-for-deployment-role.yml
  workflow_dispatch:
    inputs:
      iamActionsRoleArn:
        description: 'IAM role ARN to assume for actions'
        type: string
        required: false
        default: ''
      iamDeploymentRoleArn:
        description: 'IAM role ARN to assume for deployment'
        type: string
        required: false
        default: ''

jobs:
  check-aws-access:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      iamActionsRoleArn: ${{ inputs.iamActionsRoleArn || 'arn:aws:iam::541134664601:role/agentic-lib-github-actions-role' }}
      iamDeploymentRoleArn: ${{ inputs.iamDeploymentRoleArn || 'arn:aws:iam::541134664601:role/intention-com-web-deployment-role' }}

    steps:

      - run: uname -a

      # See: https://github.com/aws-actions/configure-aws-credentials
      # See: https://www.eliasbrange.dev/posts/secure-aws-deploys-from-github-actions-with-oidc/#:~:text=To%20be%20able%20to%20authenticate,Provider%20type%2C%20select%20OpenID%20Connect.
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.iamActionsRoleArn }}
          role-chaining: false
          aws-region: eu-west-2
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - run: aws sts get-caller-identity

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.iamDeploymentRoleArn }}
          role-chaining: true
          aws-region: eu-west-2
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - run: aws --version
      - run: aws sts get-caller-identity
      - run: aws s3 ls
