name: Check AWS deployment credentials

on:
  workflow_dispatch:

jobs:
  check-aws-access:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

      - run: uname -a

      # See: https://github.com/aws-actions/configure-aws-credentials
      # See: https://www.eliasbrange.dev/posts/secure-aws-deploys-from-github-actions-with-oidc/#:~:text=To%20be%20able%20to%20authenticate,Provider%20type%2C%20select%20OpenID%20Connect.
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::541134664601:role/xn--intenton-z2a-web-deployment-role

      - run: aws --version
      - run: aws sts get-caller-identity
      - run: aws s3 ls
