name: Build and deploy dev
concurrency: build-deploy-or-infrastructure

on:
  push:
    paths-ignore:
      - './LICENSE'
      - './README.md'
      - '.github/workflows/check*.yml'
      - '.github/workflows/infrastructure*.yml'
      - '.gitignore'
      - './deployment/src/test/**'
      - './infrastructure/**'
      - './*.sh'
    branches:
      - main
  workflow_dispatch:

jobs:
  dev-build-deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          check-latest: true

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
          check-latest: true

      - name: Install AWS CDK
        run: npm install -g aws-cdk ;

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::541134664601:role/intention-com-web-deployment-role

      - name: Check AWS CLI version
        run: aws --version ; echo ;

      - name: Check Java and Maven versions
        run: ./mvnw --version ; echo ;

      - name: Check Node version
        run:  node --version ;

      - name: Check AWS CDK versions
        run: cdk --version ; echo ;

      - name: Check AWS authentication
        run: aws sts get-caller-identity ;

      - name: Build & test
        run: ./mvnw clean install ;

      - name: Log Network stack CloudFormation template
        run: cd ./network-stack ; export TARGET_ENV='dev' ; cdk synth ;

      - name: Log Telemetry stack CloudFormation template
        run: cd ./telemetry-stack ; export TARGET_ENV='dev' ; cdk synth ;

      - name: Log Application stack CloudFormation template
        run: cd ./application-stack ; export TARGET_ENV='dev' ; cdk synth ;

      # TODO: Re-instate this step when the IAM permissions are fixed
      - name: Deploy Network stack
        run: cd ./network-stack ; export TARGET_ENV='dev' ; cdk deploy --require-approval never ;

      - name: Deploy Telemetry stack
        run: cd ./telemetry-stack ; export TARGET_ENV='dev' ; cdk deploy --require-approval never ;

      # TODO: Re-instate this step when the IAM permissions are fixed
      #- name: Deploy Application stack
      #  run: cd ./application-stack ; export TARGET_ENV='dev' ; cdk deploy --require-approval never ;
