# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2025-2026 Polycode Limited
name: Destroy dev

on:
  workflow_dispatch:
    inputs:
      iamActionsRoleArn:
        description: 'IAM role ARN to assume for actions'
        type: string
        required: false
        default: ''
      iamDeploymentRoleArn:
        description: 'IAM role ARN to assume for deployment'
        type: string
        required: false
        default: ''

jobs:
  dev-destroy:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      iamActionsRoleArn: ${{ inputs.iamActionsRoleArn || 'arn:aws:iam::541134664601:role/agentic-lib-github-actions-role' }}
      iamDeploymentRoleArn: ${{ inputs.iamDeploymentRoleArn || 'arn:aws:iam::541134664601:role/intention-com-web-deployment-role' }}

    steps:

      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          check-latest: true

      - run: npm ci || npm install

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
          check-latest: true

      #- name: download-dependencies
      #  id: download-dependencies
      #  shell: bash
      #  run: ./mvnw --batch-mode --quiet dependency:go-offline > /dev/null 2>&1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.iamActionsRoleArn }}
          role-chaining: false
          aws-region: eu-west-2
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - run: aws sts get-caller-identity

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.iamDeploymentRoleArn }}
          role-chaining: true
          aws-region: eu-west-2
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - name: Build & test
        run: ./mvnw clean install ;

      - name: Destroy Network stack
        run: cd network-stack ; export TARGET_ENV='dev' ; npx cdk destroy --require-approval never --force ;

      - name: Destroy Telemetry stack
        run: cd telemetry-stack ; export TARGET_ENV='dev' ; npx cdk destroy --require-approval never --force ;

      - name: Destroy Application stack
        run: cd application-stack ; export TARGET_ENV='dev' ; npx cdk destroy --require-approval never --force ;
