# .github/workflows/infrastructure-destroy.yml
#
# agentic-lib
# Copyright (C) 2025 Polycode Limited
#
# This file is part of agentic-lib.
#
# agentic-lib is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License v3.0 (GPL‑3).
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# IMPORTANT: Any derived work must include the following attribution:
# "This work is derived from https://github.com/xn-intenton-z2a/agentic-lib"
#

name: Destroy infrastructure
concurrency: build-deploy-or-infrastructure

on:
  workflow_dispatch:
    inputs:
      iamActionsRoleArn:
        description: 'IAM role ARN to assume for actions'
        type: string
        required: false
        default: ''
      iamInfrastructureRoleArn:
        description: 'IAM role ARN to assume for infrastructure'
        type: string
        required: false
        default: ''

jobs:
  terragrunt-destroy:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      iamActionsRoleArn: ${{ inputs.iamActionsRoleArn || 'arn:aws:iam::541134664601:role/agentic-lib-github-actions-role' }}
      iamInfrastructureRoleArn: ${{ inputs.iamInfrastructureRoleArn || 'arn:aws:iam::541134664601:role/intention-com-web-infrastructure-role' }}

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install Terraform
        run: sudo apt-get install -y wget &&
          wget https://releases.hashicorp.com/terraform/1.11.4/terraform_1.11.4_linux_386.zip --output-document ./terraform.zip &&
          unzip ./terraform.zip &&
          chmod u+x ./terraform &&
          ./terraform version

      - name: Install Terragrunt
        run: sudo apt-get install -y wget &&
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.78.2/terragrunt_linux_386 --output-document ./terragrunt &&
          chmod u+x ./terragrunt &&
          ./terragrunt --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.iamActionsRoleArn }}
          role-chaining: false
          aws-region: eu-west-2
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - run: aws sts get-caller-identity

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.iamInfrastructureRoleArn }}
          role-chaining: true
          aws-region: eu-west-2
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - name: Terragrunt destroy
        run: ./terragrunt destroy -auto-approve --terragrunt-non-interactive --terragrunt-working-dir ./infrastructure
