# .github/workflows/live-build-deploy.yml
#
# agentic-lib
# Copyright (C) 2025 Polycode Limited
#
# This file is part of agentic-lib.
#
# agentic-lib is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License v3.0 (GPL‑3).
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# IMPORTANT: Any derived work must include the following attribution:
# "This work is derived from https://github.com/xn-intenton-z2a/agentic-lib"
#

name: Build and deploy live
concurrency: build-deploy-or-infrastructure

on:
  #push:
  #  paths-ignore:
  #    - './LICENSE'
  #    - './README.md'
  #    - '.github/workflows/check*.yml'
  #    - '.github/workflows/infrastructure*.yml'
  #    - '.gitignore'
  #    - './deployment/src/test/**'
  #    - './infrastructure/**'
  #    - './*.sh'
  #  branches:
  #    - main
  workflow_dispatch:
    inputs:
      iamActionsRoleArn:
        description: 'IAM role ARN to assume for actions'
        type: string
        required: false
        default: ''
      iamDeploymentRoleArn:
        description: 'IAM role ARN to assume for deployment'
        type: string
        required: false
        default: ''

jobs:
  live-build-deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      iamActionsRoleArn: ${{ inputs.iamActionsRoleArn || 'arn:aws:iam::541134664601:role/agentic-lib-github-actions-role' }}
      iamDeploymentRoleArn: ${{ inputs.iamDeploymentRoleArn || 'arn:aws:iam::541134664601:role/intention-com-web-deployment-role' }}

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci || npm install

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      #- name: download-dependencies
      #  id: download-dependencies
      #  shell: bash
      #  run: ./mvnw --batch-mode --quiet dependency:go-offline > /dev/null 2>&1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.iamActionsRoleArn }}
          role-chaining: false
          aws-region: eu-west-2
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - run: aws sts get-caller-identity

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.iamDeploymentRoleArn }}
          role-chaining: true
          aws-region: eu-west-2
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - name: Check AWS CLI version
        run: aws --version ; echo ;

      - name: Check Java and Maven versions
        run: ./mvnw --version ; echo ;

      - name: Check Node version
        run:  node --version ;

      - name: Check AWS CDK versions
        run: npx cdk --version ; echo ;

      - name: Check AWS authentication
        run: aws sts get-caller-identity ;

      - name: Build & test
        run: ./mvnw clean install ;

      - name: Log Network stack CloudFormation template
        run: cd ./network-stack ; export TARGET_ENV='live' ; npx cdk synth ;

      - name: Log Telemetry stack CloudFormation template
        run: cd ./telemetry-stack ; export TARGET_ENV='live' ; npx cdk synth ;

      - name: Log Application stack CloudFormation template
        run: cd ./application-stack ; export TARGET_ENV='live' ; npx cdk synth ;

      - name: Deploy Network stack
        run: cd ./network-stack ; export TARGET_ENV='live' ; npx cdk deploy --require-approval never ;

      - name: Deploy Telemetry stack
        run: cd ./telemetry-stack ; export TARGET_ENV='live' ; npx cdk deploy --require-approval never ;

      - name: Deploy Application stack
        run: cd ./application-stack ; export TARGET_ENV='live' ; npx cdk deploy --require-approval never ;
